# Generated by Django 4.2.1 on 2023-05-15 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=180, verbose_name='Адресс')),
                ('card_num', models.IntegerField(max_length=50, verbose_name='Номер карты')),
                ('cvv', models.IntegerField(max_length=30, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Платежный адрес',
                'verbose_name_plural': 'Платежные адреса',
            },
        ),
    ]
