# Generated by Django 4.2.1 on 2023-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='card_num',
            field=models.IntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='cvv',
            field=models.IntegerField(verbose_name='CVV'),
        ),
    ]
